name: Build Atmosphère

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:22.04

    steps:
    - name: Checkout Atmosphère
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
          python3 python3-pip curl unzip zip git build-essential gnupg

    - name: Upgrade pip and install Python deps
      run: |
        python3 -m pip install --upgrade pip
        pip3 install lz4

    - name: Install devkitPro toolchain
      run: |
        curl -L https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.deb -o devkitpro-pacman.deb
        dpkg -i devkitpro-pacman.deb || apt-get install -f -y
        dkp-pacman -Sy --noconfirm
        dkp-pacman -S --noconfirm devkitA64 libnx

        echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
        echo "DEVKITA64=/opt/devkitpro/devkitA64" >> $GITHUB_ENV
        echo "/opt/devkitpro/devkitA64/bin" >> $GITHUB_PATH

    - name: Verify toolchain
      run: |
        echo "DEVKITPRO=$DEVKITPRO"
        echo "DEVKITA64=$DEVKITA64"
        which aarch64-none-elf-gcc
        aarch64-none-elf-gcc --version

    - name: Build Atmosphère
      run: |
        make nx_release

    - name: Unzip and repackage Atmosphère
      run: |
        release_dir=$(find out -type d -path "out/nintendo_*/release" | head -n 1)
        zip_file=$(find "$release_dir" -name "atmosphere-*.zip" ! -name "*debug.zip" | head -n 1)
        echo "Found zip: $zip_file"
        zip_name=$(basename "$zip_file" .zip)
        echo "ZIP_NAME=$zip_name" >> $GITHUB_ENV
        echo "ZIP_FILE=$zip_file" >> $GITHUB_ENV
        mkdir -p unpacked
        unzip -q "$zip_file" -d unpacked
        cp "$release_dir/fusee.bin" unpacked/
        cd unpacked
        zip -rq ../${zip_name}.zip .
        cd -

    - name: Set tag and release name
      run: |
        echo "TAG_NAME=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
        echo "RELEASE_NAME=${{ env.ZIP_NAME }} | $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        tag: ${{ env.TAG_NAME }}
        allowUpdates: true
        commit: master
        token: ${{ secrets.actions_release }}
        body: "最新构建版本，包含 atmosphere文件夹、switch文件夹、fusee.bin"
        artifacts: ${{ env.ZIP_NAME }}.zip

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.actions_release }}

    - name: Trigger repository workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.actions_release }}
        repository: T-DeBuger/SwitchNX
        event-type: build-complete
