name: Build Atmosphère

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: devkitpro/devkita64:latest

    steps:
    - name: Checkout Atmosphère
      uses: actions/checkout@v3

    - name: Cache build output
      uses: actions/cache@v3
      with:
        path: out
        key: ${{ runner.os }}-atmosphere-build-${{ hashFiles('**/*.c', '**/*.cpp', '**/*.h', 'Makefile') }}
        restore-keys: |
          ${{ runner.os }}-atmosphere-build-

    - name: Install pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        python3 -m pip install --upgrade pip

    - name: Install Python dependencies
      run: |
        pip3 install lz4

    - name: Build Atmosphère
      run: |
        make nx_release

    - name: Unzip and repackage Atmosphère
      run: |
        release_dir=$(find out -type d -path "out/nintendo_*/release" | head -n 1)
        zip_file=$(find "$release_dir" -name "atmosphere-*.zip" | head -n 1)
        echo "Found zip: $zip_file"

        zip_name=$(basename "$zip_file" .zip)
        echo "ZIP_NAME=$zip_name" >> $GITHUB_ENV
        echo "ZIP_FILE=$zip_file" >> $GITHUB_ENV

        mkdir -p unpacked
        unzip -q "$zip_file" -d unpacked
        cp "$release_dir/fusee.bin" unpacked/
        cd unpacked
        zip -rq ../atmosphere.zip .
        cd -

    - name: Set tag and release name
      run: |
        echo "TAG_NAME=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
        echo "RELEASE_NAME=${{ env.ZIP_NAME }} $(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.RELEASE_NAME }}
        tag: ${{ env.TAG_NAME }}
        allowUpdates: false
        commit: master
        token: ${{ secrets.actions_release }}
        body: "最新构建版本，包含 atmosphere.zip 和 fusee.bin"
        artifacts: atmosphere.zip

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.actions_release }}

    - name: Trigger repository workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.actions_release }}
        repository: T-DeBuger/SwitchNX
        event-type: build-complete
